export const SET_MINI_DIALOG = 'SET_MINI_DIALOG'
export const SHOW_MINI_DIALOG = 'SHOW_MINI_DIALOG'
export const SET_FULL_DIALOG = 'SET_FULL_DIALOG'
export const SHOW_FULL_DIALOG = 'SHOW_FULL_DIALOG'
